fix: log missing repo directories instead of exiting
A missing directory happens due to many reasons including missing
translations in the repository.

This can be painful to fix for maintainers, so `atlas` should recover
from this error by skipping the missing directory,
logging it and resuming the copying process.

Refs: FC-0012 OEP-58

diff --git a/atlas b/atlas
--- a/atlas
+++ b/atlas
@@ -278,6 +278,13 @@ contains_substring() {
   return $?
 }
 
+directory_exists() {
+  # Checks if directory ($1) exists
+  # This is mainly used to be mocked in tests
+  test -d "$1"
+  return $?
+}
+
 display_pull_params() {
   # Output configured vars to user
   echo "Pulling translation files"
@@ -395,7 +402,16 @@ pull_translations() {
       echo "Done."
       echo "Copying translations from \"${directory_from}\" to \"./${directory_to}\"..."
     fi
-    cp -r "${directory_from}"/* "${directory_to}"/ || exit 1
+
+    if directory_exists "$directory_from";
+    then
+      cp -r "${directory_from}"/* "${directory_to}"/ || exit 1
+    else
+      if [ -z "$SILENT" ];
+      then
+        echo "Skipped copying \"${directory_from}\" because it was not found in the repository."
+      fi
+    fi
   done
 
   # finished "Copying translations from <temp dir> to <dest dir>..." step
